{
 "title": "HP Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HP Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drive Status (hpacucli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_drive",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "drive" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpacucli",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "Power Draw (hpasmcli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_supply",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "supply" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpasmcli.draw",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "Power Supply Status (hpasmcli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_supply",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "supply" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpasmcli.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "Temperature (hpasmcli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpasmcli.temp",
     "query": "SELECT mean(\"value\") FROM \"hpasmcli.temp\" WHERE (\"host\" = '$hostname') AND $timeFilter GROUP BY time(1m), \"sensor\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "1-AMBIENT" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "11-MEMORY_BD" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "15-POWER_SUPPLY_BAY" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "3-PROCESSOR_ZONE" }
     ]
    }
   ]
  },
  {
   "title": "Fan Status (hpasmcli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_fan",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "fan" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpasmcli.fan.redundant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed (hpasmcli)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_fan",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "fan" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hpasmcli.fan.speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  }
 ]
}